language: groovy
branches:
  only:
  - master
  - develop
env:
  global:
  - secure: Hl0jW34ahqG/+w6Nsf0IdkZjNNLQ7rm0Af9TBb8fEpUQDP3orvtAlGzkxDBdPuybawbSACsUV1UNZor+u6NuWX6TvfUCU40rhDXWkdj7TG6tKbGlnLBv/vaPekx8oo9x4C5Vv+tRZ1Kbs/kW5DlbJPzc0LsKXOIjwcgyVGQcHaE=
  - secure: DSMR4azxZKOM1yUBImIj2+xlOgaA3rWlAyJeCJR6aIKhwR/F2FHXyAfc1bxAtjLf9zqXJU7HGQL4YD48rJh/5LRLh3L7Fsww586FhgeRrQ3EQoKeFJXepVX5yXQ8tDpbO/PbjO7ZdvhkXtbR3vaMJt9NBd/+gtkVhg8kgtvex/o=
  - secure: KlDNir6qXOVmAoltbKBshTQ9+esM3q8VfHj0zJbodSzfJ+7fyUW29rRsfjthYznDaBR8Ubr1HIY/Zmmo/I3yfTN9cH5BTyHc0XmPNrgb1cZU/Dt8TSRqCsFXOkiVd5RL4Xj/TvZ58fDoYhkEA5aE/dDXoJYQxc1ZS+dL46hzepQ=
  - secure: DSKaNpTVg52SWDvtvT5ZzUcQSgs5SCWD1ysH2XpzdrWevUf7vqsYuO1HAGV3agjeodM5NjelzxT7KV7SWiRdCHwx2KvZlUJ7loPita/UDlpvxbwjN95rb/91KyvYEGkf3CXkArA4VhzKi1Cx+uXPJX7P2+xu+l6sw7FmEOhtaks=
  - secure: M5yKMy6BNCEtzWsQqQXQ0wd5Idksi2Yfk4CyVFjmAdd+J0qjscHK3YS70PSIFN9qylgMrJyn/iPJPi+J7hV+0x4qhWHn7wy80CYlkDf3e1pAvFqgERNJiKNdTMb2zZzbL6WOPWo8jRCtu4/zxrBjLq02W2WPyAkiTQiUpop3jss=
  - secure: J/N+eE60dqZJ7e+IUziCQfsuR2kS/tg9w8/ZSLEYH+AaKB384Gwq1vRyCzBLtRcZm0GgVYFb/E1DNjQJhkn2ES3Iz3Fn/bSawlMJLxeMIXJGXeCf9sja+Ci+smmTQyspQ/DuR09lWKplvZqaK+7uhoMUazrSpvcU7pseibnKFLE=
before_install:
- chmod a+x ./deploy.sh
script:
- mvn clean test --settings settings.xml
after_success:
- if [ "$TRAVIS_BRANCH" == "master"] ; then ./deploy.sh ; fi

