language: java
branches:
  only:
  - develop
  - master
  - /^release.*/
env:
  global:
  - secure: SPcGHXg5BWuIUEGU4LVXVvetGZKv4l7w5tp2US0B0v03/ag8MR9aumORks31MQlyWr08o2GZ6VRE7a5G9nPVNAHSELVa8Z+RiHN0LeLGkGS9X4TM6p4vc+6d1Zf09jFILZtvDhtlymq6EKJOeamMHQOdfaTGVQpdpUihz+JBnHE=
  - secure: eNMs+B8m3vp77uvPox91ZJy0ZLU6UpPK3w9H3z7szfPuCElWIWixySCpP+rkQWxJrAkevNezn4ts0kYWgIJaLJFxc5OkREmMzSNa3UQ8CbDR1s39LadlFku8osIjUlx95HpqxNSrDus7Xkzu/Idbt1PDh/js/4gcCjwrIEGVnAg=
  - secure: a7mJzxd8erM6Yy1NjHyTh5nGo2719xMzYzJtg5VRtI7BQtGGcNhT+5+luThbOH5RTNsrYBXsyQlYH/OR6F21TRo4G8+M+a9EpA2pn7Iiiyn73p+KYuI6MRIifDSf0ZAJSgb1EuNVbZ8Uc1BJmR0qg0TMQd6omoieOuh3cZ9bSIA=
  - secure: KJUD+LO8JNMq9TJIDlEbInI9WMA/LEN6diTso54zUbAnFghtngKgTkIwC7nYmmQG+NumBnUeMZd0N9z+p4pqjOVwqzjK8N8Ebl7AR5XqAd8UIVBr4wR4FWu1Ka/YXAiIqO0z1mzvihFoXdJK6YF/MhY3S7n+/XwkdugYqCeG+2w=
  - secure: N5nDwOMugJAJrKM4jVFDtQHsZG76wwfoFuV3kBQmOWaVdYpZpTidm6TL7QXkMsgO/u4chF7EXSv0BHGV4hnsDnhFtPF7bn8M40FnEPGiSkt3BwJBwq2yoPc3zcA+3dQGyiINWpNQ+FrKd4pe6JuEtCIqaW7xpXzo/ldei9py75k=
  - secure: E9aFbPsD5QgeHNVAwpeklNiZhIUmnCD89rF+H09vJ0I3j/RKFhkRkv+e1tJjj4TLfgD6N3mFd9NzmVil/jiLbeTmE43F0MoLjMivsP/ie7vQH7KXUdPKf/vTdKxQfGi0zn40pcGYxpKAy85tVvw8jDdqKxPGTaqOcivl+z6zU8g=
stages:
- name: Unit Tests
  if: branch = develop
- name: Staging
  if: branch =~ ^release
- name: Master
  if: branch = master
jobs:
  include:
  - stage: Unit Tests
    install: mvn --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
      -Pdevelop -B -V install
    script: mvn --settings settings.xml -Pdevelop clean test
  - stage: Staging
    before-install: chmod +x ./deploy.sh
    install: mvn --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
      -Pstaging -B -V install
    script: mvn --settings settings.xml -Dmaven.javadoc.skip=true -Pstaging -B -V
      clean test
    after_success: "./deploy.sh"
  - stage: Master
    install: mvn --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
      -B -V install
    script: mvn --settings settings.xml clean test
